# Generated by Django 5.1.2 on 2024-10-24 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("booking", "0001_initial"),
        ("field", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="field.field",
            ),
        ),
    ]
