# Generated by Django 5.1.2 on 2024-10-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
                ("contact_info", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
                ("available_from", models.TimeField()),
                ("available_to", models.TimeField()),
                (
                    "price_per_hour",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "images",
                    models.ImageField(
                        blank=True, null=True, upload_to="fields_images/"
                    ),
                ),
            ],
        ),
    ]
